# Generated by Django 2.0.4 on 2018-07-16 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriaproduto',
            fields=[
                ('pkid_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nomecategoria', models.CharField(max_length=100, unique=True)),
                ('hide', models.BooleanField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cotacaocompra',
            fields=[
                ('pkid_cotacao', models.AutoField(primary_key=True, serialize=False)),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True)),
                ('dt_cotacao', models.DateTimeField(blank=True, null=True)),
                ('dt_entrega', models.DateTimeField(blank=True, null=True)),
                ('formapamento', models.CharField(blank=True, max_length=45, null=True)),
                ('pedidocompra_pkid_compra', models.IntegerField()),
                ('statuscotacao_pkid_status', models.IntegerField()),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, null=True)),
                ('hide', models.TextField(blank=True, default=0, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('pkid_endereco', models.AutoField(primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=100)),
                ('numero', models.CharField(blank=True, max_length=7, null=True)),
                ('complemento', models.CharField(blank=True, max_length=45, null=True)),
                ('cep', models.CharField(max_length=9)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=150)),
                ('uf', models.CharField(max_length=2)),
                ('hide', models.BooleanField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('pkid_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('dataentrega', models.DateTimeField(blank=True, null=True)),
                ('formaentrega', models.CharField(blank=True, max_length=100, null=True)),
                ('valorfrete', models.TextField(blank=True, null=True)),
                ('nomecontarecebimento', models.CharField(blank=True, max_length=100, null=True)),
                ('fkid_usuario_alteracao', models.IntegerField()),
                ('dt_cadastro', models.DateTimeField()),
                ('dt_alteracao', models.DateTimeField()),
                ('hide', models.TextField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Formapagamento',
            fields=[
                ('pkid_formapag', models.AutoField(primary_key=True, serialize=False)),
                ('formapagamento', models.CharField(max_length=50)),
                ('fkid_usuario_alteracao', models.IntegerField()),
                ('dt_cadastro', models.DateTimeField()),
                ('dt_alteracao', models.DateTimeField()),
                ('hide', models.TextField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Formula_materia',
            fields=[
                ('pkid_formula_materia', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Formulaproduto',
            fields=[
                ('pkid_formula', models.AutoField(primary_key=True, serialize=False)),
                ('fkid_produto', models.IntegerField()),
                ('tempomaturacao', models.IntegerField(blank=True, null=True)),
                ('fkid_usuario_alteracao', models.IntegerField()),
                ('dt_cadastro', models.DateTimeField()),
                ('dt_alteracao', models.DateTimeField()),
                ('hide', models.TextField(default=0)),
                ('fkid_formula_materia', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Formula_materia')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itemcompra',
            fields=[
                ('pkid_item', models.AutoField(primary_key=True, serialize=False)),
                ('produto', models.CharField(blank=True, max_length=45, null=True)),
                ('descricaoproduto', models.CharField(blank=True, max_length=45, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('precounitario', models.TextField(blank=True, null=True)),
                ('totalvenda', models.TextField(blank=True, null=True)),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, null=True)),
                ('hide', models.TextField(blank=True, default=0, null=True)),
                ('pedidocompra_pkid_compra', models.IntegerField()),
                ('statuscompra_pkid_status', models.IntegerField()),
                ('unidademedidacompra_pkid_unidademedida', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itemcotacao',
            fields=[
                ('pkid_item', models.AutoField(primary_key=True, serialize=False)),
                ('produto', models.CharField(blank=True, max_length=45, null=True)),
                ('descricaoproduto', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('precounitario', models.TextField(blank=True, null=True)),
                ('totalvenda', models.TextField(blank=True, null=True)),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, null=True)),
                ('hide', models.TextField(blank=True, default=0, null=True)),
                ('cotacaocompra_pkid_cotacao', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itemvenda',
            fields=[
                ('pkid_item', models.AutoField(max_length=45, primary_key=True, serialize=False)),
                ('pedido_venda_idpedido_venda', models.IntegerField()),
                ('produto', models.CharField(blank=True, max_length=45, null=True)),
                ('descricaoproduto', models.CharField(blank=True, max_length=45, null=True)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('unidademedida_pkid_unidademedida', models.IntegerField()),
                ('precounitario', models.TextField(blank=True, null=True)),
                ('totalvenda', models.TextField(blank=True, null=True)),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, null=True)),
                ('hide', models.TextField(blank=True, default=0, null=True)),
                ('produtos_idprodutos', models.IntegerField()),
                ('usuario_pkid_usuario', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Linhavenda',
            fields=[
                ('pkid_linhavenda', models.AutoField(primary_key=True, serialize=False)),
                ('pedidovenda_pkid_venda', models.IntegerField()),
                ('fkid_produto', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('precovenda', models.TextField()),
                ('fkid_usuario_alteracao', models.IntegerField()),
                ('dt_alteracao', models.DateTimeField()),
                ('dt_cadastro', models.DateTimeField()),
                ('hide', models.TextField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materiaprima',
            fields=[
                ('pkid_materiaprima', models.AutoField(primary_key=True, serialize=False)),
                ('materiaprima', models.CharField(blank=True, max_length=100, null=True)),
                ('totalestoque', models.IntegerField()),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, null=True)),
                ('fkid_estoque', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('pkid_movimentacao', models.AutoField(primary_key=True, serialize=False)),
                ('fkid_produto', models.IntegerField()),
                ('tipomovimentacao', models.TextField()),
                ('numentradas', models.IntegerField()),
                ('numsaidas', models.IntegerField()),
                ('dt_cadastro', models.DateTimeField()),
                ('dt_alteracao', models.DateTimeField()),
                ('hide', models.TextField(default=0)),
                ('fkid_linhavenda1', models.IntegerField(blank=True, null=True)),
                ('fkid_venda', models.IntegerField(blank=True, null=True)),
                ('fkid_pedidofabri', models.IntegerField(blank=True, null=True)),
                ('fkid_estoque', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedidocompra',
            fields=[
                ('pkid_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fornecedor', models.CharField(blank=True, max_length=100, null=True)),
                ('dt_pedido', models.DateTimeField(blank=True, null=True)),
                ('dt_compra', models.DateTimeField(blank=True, null=True)),
                ('dt_pagamento', models.DateTimeField(blank=True, null=True)),
                ('dt_recebimento', models.DateTimeField(blank=True, null=True)),
                ('cotacaocompra_pkid_cotacao', models.IntegerField()),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, null=True)),
                ('hide', models.TextField(blank=True, default=0, null=True)),
                ('statuscompra_pkid_status', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedidofabricacao',
            fields=[
                ('pkid_pedidofabri', models.AutoField(primary_key=True, serialize=False)),
                ('fkid_produto', models.IntegerField()),
                ('fkid_usuario_alteracao', models.IntegerField()),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, null=True)),
                ('hide', models.TextField(blank=True, default=0, null=True)),
                ('fkid_statusfabricacao', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedidovenda',
            fields=[
                ('pkid_venda', models.AutoField(primary_key=True, serialize=False)),
                ('fkid_pessoa', models.IntegerField()),
                ('fkid_usuario', models.IntegerField()),
                ('dt_pedido', models.DateTimeField(blank=True, null=True)),
                ('dt_pagamento', models.DateTimeField(blank=True, null=True)),
                ('dt_entrega', models.DateTimeField(blank=True, null=True)),
                ('fkid_usuarioalteracao', models.IntegerField()),
                ('fkid_formapag', models.IntegerField()),
                ('fkid_entrega', models.IntegerField()),
                ('dt_cadastro', models.DateTimeField()),
                ('dt_alteracao', models.DateTimeField()),
                ('hide', models.TextField(default=0)),
                ('fkid_status', models.IntegerField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('pkid_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nomecompleto_razaosocial', models.CharField(max_length=100)),
                ('apelido_nomefantasia', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=19, null=True, unique=True)),
                ('rg_ie', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(max_length=1)),
                ('dt_nascimento', models.DateField(blank=True, null=True)),
                ('st_pessoajuridica', models.BooleanField(default=0, max_length=1)),
                ('tipopessoa', models.CharField(max_length=15)),
                ('hide', models.BooleanField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('pkid_produto', models.AutoField(primary_key=True, serialize=False)),
                ('codproduto', models.CharField(max_length=8, unique=True)),
                ('nomeproduto', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precocusto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('totalestoque', models.IntegerField(default=0)),
                ('descricao', models.CharField(blank=True, max_length=300, null=True)),
                ('sabor', models.CharField(blank=True, max_length=45, null=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('altura', models.IntegerField()),
                ('largura', models.IntegerField()),
                ('profundidade', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=3, max_digits=10)),
                ('fotoproduto', models.FileField(blank=True, max_length=1000, null=True, upload_to='uploads/%Y/%m')),
                ('hide', models.BooleanField(default=0)),
                ('fkid_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Categoriaproduto')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statuscompra',
            fields=[
                ('pkid_status', models.AutoField(primary_key=True, serialize=False)),
                ('descricaostatus', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statusfabricacao',
            fields=[
                ('pkid_status', models.AutoField(primary_key=True, serialize=False)),
                ('descricaostatus', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statusvenda',
            fields=[
                ('pkid_status', models.AutoField(primary_key=True, serialize=False)),
                ('descricaostatus', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('pkid_telefone', models.AutoField(primary_key=True, serialize=False)),
                ('ddi', models.CharField(default=55, max_length=2)),
                ('ddd', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=15)),
                ('hide', models.TextField(default=0)),
                ('fkid_pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Pessoa')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Unidademedida',
            fields=[
                ('pkid_unidademedida', models.AutoField(primary_key=True, serialize=False)),
                ('unidademedida', models.CharField(max_length=50, unique=True)),
                ('hide', models.BooleanField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('pkid_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nomecompleto', models.CharField(max_length=45)),
                ('login', models.CharField(max_length=45, unique=True)),
                ('senha', models.CharField(max_length=45)),
                ('dt_importacao', models.DateTimeField()),
                ('dt_alteracao', models.DateTimeField()),
                ('hide', models.TextField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarioalteracao',
            fields=[
                ('pkid_usuario_alteracao', models.AutoField(primary_key=True, serialize=False)),
                ('dt_alteracao', models.DateTimeField()),
                ('tipo_alteracao', models.TextField()),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='fkid_unidademedida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Unidademedida'),
        ),
        migrations.AlterUniqueTogether(
            name='linhavenda',
            unique_together={('pkid_linhavenda', 'pedidovenda_pkid_venda')},
        ),
        migrations.AlterUniqueTogether(
            name='itemvenda',
            unique_together={('pkid_item', 'pedido_venda_idpedido_venda')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcotacao',
            unique_together={('pkid_item', 'cotacaocompra_pkid_cotacao')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcompra',
            unique_together={('pkid_item', 'pedidocompra_pkid_compra')},
        ),
        migrations.AddField(
            model_name='formula_materia',
            name='fkid_formulaproduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Formulaproduto'),
        ),
        migrations.AddField(
            model_name='formula_materia',
            name='fkid_materiaprima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.Materiaprima'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='fkid_pessoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Pessoa'),
        ),
    ]
