# Generated by Django 2.0.4 on 2018-10-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidofabricacao',
            name='lote',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pedidofabricacao',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
    ]
