# Generated by Django 2.0.4 on 2018-07-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180710_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidademedida',
            name='pkid_unidademedida',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
