# Generated by Django 2.0.4 on 2018-09-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180926_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrega',
            options={'managed': True, 'verbose_name': 'Forma de Entrega', 'verbose_name_plural': 'Formas de Entrega'},
        ),
        migrations.AlterModelOptions(
            name='formapagamento',
            options={'managed': True, 'verbose_name': 'Forma de Pagamento', 'verbose_name_plural': 'Formas de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='pedidovenda',
            options={'managed': True, 'verbose_name': 'Pedido de Venda', 'verbose_name_plural': 'Pedidos de Venda'},
        ),
        migrations.AlterModelOptions(
            name='statusvenda',
            options={'managed': True, 'verbose_name': 'Status de Venda', 'verbose_name_plural': 'Status de Venda'},
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='dt_alteracao',
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='dt_cadastro',
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='unidademedida_pkid_unidademedida',
        ),
        migrations.RemoveField(
            model_name='itemvenda',
            name='usuario_pkid_usuario',
        ),
        migrations.RemoveField(
            model_name='statusvenda',
            name='descricaostatus',
        ),
        migrations.AddField(
            model_name='statusvenda',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cotacaocompra',
            name='hide',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='entrega',
            name='hide',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='itemcompra',
            name='hide',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='itemcotacao',
            name='hide',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='hide',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='precounitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='linhavenda',
            name='hide',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='hide',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pedidocompra',
            name='hide',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='pedidovenda',
            name='hide',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='hide',
            field=models.BooleanField(default=0),
        ),
    ]
