# Generated by Django 2.0.4 on 2018-07-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180711_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pkid_produto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipopessoa',
            name='pkid_tipopessoa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
