# Generated by Django 2.0.4 on 2018-06-05 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codename', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
                ('last_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
                ('action_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoriaproduto',
            fields=[
                ('pkid_categoria', models.IntegerField(db_column='PKID_Categoria', primary_key=True, serialize=False)),
                ('nomecategoria', models.CharField(db_column='NomeCategoria', max_length=100, unique=True)),
                ('hide', models.BooleanField(db_column='HIDE')),
            ],
            options={
                'db_table': 'CategoriaProduto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cotacaocompra',
            fields=[
                ('pkid_cotacao', models.IntegerField(db_column='PKID_Cotacao', primary_key=True, serialize=False)),
                ('fornecedor', models.CharField(blank=True, db_column='Fornecedor', max_length=100, null=True)),
                ('dt_cotacao', models.DateTimeField(blank=True, db_column='DT_Cotacao', null=True)),
                ('dt_entrega', models.DateTimeField(blank=True, db_column='DT_entrega', null=True)),
                ('formapamento', models.CharField(blank=True, db_column='FormaPamento', max_length=45, null=True)),
                ('pedidocompra_pkid_compra', models.IntegerField(db_column='PedidoCompra_PKID_Compra')),
                ('statuscotacao_pkid_status', models.IntegerField(db_column='StatusCotacao_PKID_Status')),
                ('dt_cadastro', models.DateTimeField(blank=True, db_column='DT_Cadastro', null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, db_column='DT_Alteracao', null=True)),
                ('hide', models.TextField(blank=True, db_column='HIDE', null=True)),
            ],
            options={
                'db_table': 'CotacaoCompra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkid_endereco', models.IntegerField(db_column='PKID_Endereco')),
                ('logradouro', models.CharField(db_column='Logradouro', max_length=100)),
                ('numero', models.CharField(db_column='Numero', max_length=7)),
                ('complemento', models.CharField(blank=True, db_column='Complemento', max_length=45, null=True)),
                ('cep', models.IntegerField(db_column='CEP')),
                ('bairro', models.CharField(db_column='Bairro', max_length=100)),
                ('cidade', models.CharField(db_column='Cidade', max_length=150)),
                ('uf', models.CharField(db_column='UF', max_length=2)),
                ('hide', models.BooleanField(db_column='HIDE')),
            ],
            options={
                'db_table': 'Endereco',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('pkid_entrega', models.IntegerField(db_column='PKID_Entrega', primary_key=True, serialize=False)),
                ('dataentrega', models.DateTimeField(blank=True, db_column='DataEntrega', null=True)),
                ('formaentrega', models.CharField(blank=True, db_column='FormaEntrega', max_length=100, null=True)),
                ('valorfrete', models.TextField(blank=True, db_column='ValorFrete', null=True)),
                ('nomecontarecebimento', models.CharField(blank=True, db_column='NomeContaRecebimento', max_length=100, null=True)),
                ('fkid_usuario_alteracao', models.IntegerField(db_column='FKID_Usuario_Alteracao')),
                ('dt_cadastro', models.DateTimeField(db_column='DT_Cadastro')),
                ('dt_alteracao', models.DateTimeField(db_column='DT_Alteracao')),
                ('hide', models.TextField(db_column='HIDE')),
            ],
            options={
                'db_table': 'Entrega',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Formapagamento',
            fields=[
                ('pkid_formapag', models.IntegerField(db_column='PKID_FormaPag', primary_key=True, serialize=False)),
                ('formapagamento', models.CharField(db_column='FormaPagamento', max_length=50)),
                ('fkid_usuario_alteracao', models.IntegerField(db_column='FKID_Usuario_Alteracao')),
                ('dt_cadastro', models.DateTimeField(db_column='DT_Cadastro')),
                ('dt_alteracao', models.DateTimeField(db_column='DT_Alteracao')),
                ('hide', models.TextField(db_column='HIDE')),
            ],
            options={
                'db_table': 'FormaPagamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Formulaproduto',
            fields=[
                ('pkid_formula', models.IntegerField(db_column='PKID_Formula', primary_key=True, serialize=False)),
                ('fkid_produto', models.IntegerField(db_column='FKID_Produto')),
                ('fkid_materiaprima', models.IntegerField(db_column='FKID_MateriaPrima')),
                ('tempomatucao', models.IntegerField(blank=True, db_column='TempoMatucao', null=True)),
                ('fkid_usuario_alteracao', models.IntegerField(db_column='FKID_Usuario_Alteracao')),
                ('dt_cadastro', models.DateTimeField(db_column='DT_Cadastro')),
                ('dt_alteracao', models.DateTimeField(db_column='DT_Alteracao')),
                ('hide', models.TextField(db_column='HIDE')),
            ],
            options={
                'db_table': 'FormulaProduto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itemcompra',
            fields=[
                ('pkid_item', models.IntegerField(db_column='PKID_Item', primary_key=True, serialize=False)),
                ('produto', models.CharField(blank=True, db_column='Produto', max_length=45, null=True)),
                ('descricaoproduto', models.CharField(blank=True, db_column='DescricaoProduto', max_length=45, null=True)),
                ('quantidade', models.IntegerField(blank=True, db_column='Quantidade', null=True)),
                ('precounitario', models.TextField(blank=True, db_column='PrecoUnitario', null=True)),
                ('totalvenda', models.TextField(blank=True, db_column='TotalVenda', null=True)),
                ('dt_cadastro', models.DateTimeField(blank=True, db_column='DT_Cadastro', null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, db_column='DT_Alteracao', null=True)),
                ('hide', models.TextField(blank=True, db_column='HIDE', null=True)),
                ('pedidocompra_pkid_compra', models.IntegerField(db_column='PedidoCompra_PKID_Compra')),
                ('statuscompra_pkid_status', models.IntegerField(db_column='StatusCompra_PKID_Status')),
                ('unidademedidacompra_pkid_unidademedida', models.IntegerField(db_column='UnidadeMedidaCompra_PKID_UnidadeMedida')),
            ],
            options={
                'db_table': 'ItemCompra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itemcotacao',
            fields=[
                ('pkid_item', models.IntegerField(db_column='PKID_Item', primary_key=True, serialize=False)),
                ('produto', models.CharField(blank=True, db_column='Produto', max_length=45, null=True)),
                ('descricaoproduto', models.CharField(blank=True, db_column='DescricaoProduto', max_length=100, null=True)),
                ('quantidade', models.IntegerField(blank=True, db_column='Quantidade', null=True)),
                ('precounitario', models.TextField(blank=True, db_column='PrecoUnitario', null=True)),
                ('totalvenda', models.TextField(blank=True, db_column='TotalVenda', null=True)),
                ('dt_cadastro', models.DateTimeField(blank=True, db_column='DT_Cadastro', null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, db_column='DT_Alteracao', null=True)),
                ('hide', models.TextField(blank=True, db_column='HIDE', null=True)),
                ('cotacaocompra_pkid_cotacao', models.IntegerField(db_column='CotacaoCompra_PKID_Cotacao')),
            ],
            options={
                'db_table': 'ItemCotacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Itemvenda',
            fields=[
                ('pkid_item', models.CharField(db_column='PKID_Item', max_length=45, primary_key=True, serialize=False)),
                ('pedido_venda_idpedido_venda', models.IntegerField()),
                ('produto', models.CharField(blank=True, db_column='Produto', max_length=45, null=True)),
                ('descricaoproduto', models.CharField(blank=True, db_column='DescricaoProduto', max_length=45, null=True)),
                ('quantidade', models.IntegerField(blank=True, db_column='Quantidade', null=True)),
                ('unidademedida_pkid_unidademedida', models.IntegerField(db_column='UnidadeMedida_PKID_UnidadeMedida')),
                ('precounitario', models.TextField(blank=True, db_column='PrecoUnitario', null=True)),
                ('totalvenda', models.TextField(blank=True, db_column='TotalVenda', null=True)),
                ('dt_cadastro', models.DateTimeField(blank=True, db_column='DT_Cadastro', null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, db_column='DT_Alteracao', null=True)),
                ('hide', models.TextField(blank=True, db_column='HIDE', null=True)),
                ('produtos_idprodutos', models.IntegerField(db_column='Produtos_idProdutos')),
                ('usuario_pkid_usuario', models.IntegerField(db_column='Usuario_PKID_Usuario')),
            ],
            options={
                'db_table': 'ItemVenda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Linhavenda',
            fields=[
                ('pkid_linhavenda', models.IntegerField(db_column='PKID_LinhaVenda', primary_key=True, serialize=False)),
                ('pedidovenda_pkid_venda', models.IntegerField(db_column='PedidoVenda_PKID_Venda')),
                ('fkid_produto', models.IntegerField(db_column='FKID_Produto')),
                ('quantidade', models.IntegerField(db_column='Quantidade')),
                ('precovenda', models.TextField(db_column='PrecoVenda')),
                ('fkid_usuario_alteracao', models.IntegerField(db_column='FKID_Usuario_Alteracao')),
                ('dt_alteracao', models.DateTimeField(db_column='DT_Alteracao')),
                ('dt_cadastro', models.DateTimeField(db_column='DT_Cadastro')),
                ('hide', models.TextField(db_column='HIDE')),
            ],
            options={
                'db_table': 'LinhaVenda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materiaprima',
            fields=[
                ('pkid_materiaprima', models.IntegerField(db_column='PKID_MateriaPrima', primary_key=True, serialize=False)),
                ('materiaprima', models.CharField(blank=True, db_column='MateriaPrima', max_length=100, null=True)),
                ('totalestoque', models.IntegerField(db_column='TotalEstoque')),
                ('dt_cadastro', models.DateTimeField(blank=True, db_column='DT_Cadastro', null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, db_column='DT_Alteracao', null=True)),
                ('fkid_estoque', models.IntegerField(db_column='FKID_Estoque')),
            ],
            options={
                'db_table': 'MateriaPrima',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('pkid_movimentacao', models.IntegerField(db_column='PKID_Movimentacao', primary_key=True, serialize=False)),
                ('fkid_produto', models.IntegerField(db_column='FKID_Produto')),
                ('tipomovimentacao', models.TextField(db_column='TipoMovimentacao')),
                ('numentradas', models.IntegerField(db_column='NumEntradas')),
                ('numsaidas', models.IntegerField(db_column='NumSaidas')),
                ('dt_cadastro', models.DateTimeField(db_column='DT_Cadastro')),
                ('dt_alteracao', models.DateTimeField(db_column='DT_Alteracao')),
                ('hide', models.TextField(db_column='HIDE')),
                ('fkid_linhavenda1', models.IntegerField(blank=True, db_column='FKID_LinhaVenda1', null=True)),
                ('fkid_venda', models.IntegerField(blank=True, db_column='FKID_Venda', null=True)),
                ('fkid_pedidofabri', models.IntegerField(blank=True, db_column='FKID_PedidoFabri', null=True)),
                ('fkid_estoque', models.IntegerField(db_column='FKID_Estoque')),
            ],
            options={
                'db_table': 'Movimentacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedidocompra',
            fields=[
                ('pkid_compra', models.IntegerField(db_column='PKID_Compra', primary_key=True, serialize=False)),
                ('fornecedor', models.CharField(blank=True, db_column='Fornecedor', max_length=100, null=True)),
                ('dt_pedido', models.DateTimeField(blank=True, db_column='DT_Pedido', null=True)),
                ('dt_compra', models.DateTimeField(blank=True, db_column='DT_Compra', null=True)),
                ('dt_pagamento', models.DateTimeField(blank=True, db_column='DT_Pagamento', null=True)),
                ('dt_recebimento', models.DateTimeField(blank=True, db_column='DT_Recebimento', null=True)),
                ('cotacaocompra_pkid_cotacao', models.IntegerField(db_column='CotacaoCompra_PKID_Cotacao')),
                ('dt_cadastro', models.DateTimeField(blank=True, db_column='DT_Cadastro', null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, db_column='DT_Alteracao', null=True)),
                ('hide', models.TextField(blank=True, db_column='HIDE', null=True)),
                ('statuscompra_pkid_status', models.IntegerField(db_column='StatusCompra_PKID_Status')),
            ],
            options={
                'db_table': 'PedidoCompra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedidofabricacao',
            fields=[
                ('pkid_pedidofabri', models.IntegerField(db_column='PKID_PedidoFabri', primary_key=True, serialize=False)),
                ('fkid_produto', models.IntegerField(db_column='FKID_Produto')),
                ('fkid_usuario_alteracao', models.IntegerField(db_column='FKID_Usuario_Alteracao')),
                ('dt_cadastro', models.DateTimeField(blank=True, db_column='DT_Cadastro', null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, db_column='DT_Alteracao', null=True)),
                ('hide', models.TextField(blank=True, db_column='HIDE', null=True)),
                ('fkid_statusfabricacao', models.IntegerField(db_column='FKID_StatusFabricacao')),
            ],
            options={
                'db_table': 'PedidoFabricacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pedidovenda',
            fields=[
                ('pkid_venda', models.IntegerField(db_column='PKID_Venda', primary_key=True, serialize=False)),
                ('fkid_pessoa', models.IntegerField(db_column='FKID_Pessoa')),
                ('fkid_usuario', models.IntegerField(db_column='FKID_Usuario')),
                ('dt_pedido', models.DateTimeField(blank=True, db_column='DT_Pedido', null=True)),
                ('dt_pagamento', models.DateTimeField(blank=True, db_column='DT_Pagamento', null=True)),
                ('dt_entrega', models.DateTimeField(blank=True, db_column='DT_Entrega', null=True)),
                ('fkid_usuarioalteracao', models.IntegerField(db_column='FKID_UsuarioAlteracao')),
                ('fkid_formapag', models.IntegerField(db_column='FKID_FormaPag')),
                ('fkid_entrega', models.IntegerField(db_column='FKID_Entrega')),
                ('dt_cadastro', models.DateTimeField(db_column='DT_Cadastro')),
                ('dt_alteracao', models.DateTimeField(db_column='DT_Alteracao')),
                ('hide', models.TextField(db_column='HIDE')),
                ('fkid_status', models.IntegerField(db_column='FKID_Status')),
            ],
            options={
                'db_table': 'PedidoVenda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('pkid_pessoa', models.IntegerField(db_column='PKID_Pessoa', primary_key=True, serialize=False)),
                ('nomecompleto_razaosocial', models.CharField(db_column='NomeCompleto_RazaoSocial', max_length=100)),
                ('apelido_nomefantasia', models.CharField(blank=True, db_column='Apelido_NomeFantasia', max_length=100, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True, unique=True)),
                ('cpf_cnpj', models.CharField(blank=True, db_column='CPF_CNPJ', max_length=19, null=True, unique=True)),
                ('rg_ie', models.CharField(blank=True, db_column='RG_IE', max_length=50, null=True)),
                ('genero', models.CharField(db_column='Genero', max_length=1)),
                ('dt_nascimento', models.DateField(blank=True, db_column='DT_Nascimento', null=True)),
                ('st_pessoajuridica', models.CharField(db_column='ST_PessoaJuridica', max_length=1)),
                ('fkid_endereco', models.IntegerField(blank=True, db_column='FKID_Endereco', null=True)),
                ('hide', models.BooleanField(db_column='HIDE')),
            ],
            options={
                'db_table': 'Pessoa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('pkid_produto', models.IntegerField(db_column='PKID_Produto', primary_key=True, serialize=False)),
                ('codproduto', models.CharField(db_column='CodProduto', max_length=8, unique=True)),
                ('nomeproduto', models.CharField(db_column='NomeProduto', max_length=50)),
                ('preco', models.DecimalField(db_column='Preco', decimal_places=2, max_digits=10)),
                ('precocusto', models.DecimalField(blank=True, db_column='PrecoCusto', decimal_places=2, max_digits=10, null=True)),
                ('totalestoque', models.IntegerField(db_column='TotalEstoque')),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=300, null=True)),
                ('sabor', models.CharField(blank=True, db_column='Sabor', max_length=45, null=True)),
                ('marca', models.CharField(blank=True, db_column='Marca', max_length=50, null=True)),
                ('altura', models.IntegerField(db_column='Altura')),
                ('largura', models.IntegerField(db_column='Largura')),
                ('profundidade', models.IntegerField(db_column='Profundidade')),
                ('peso', models.DecimalField(db_column='Peso', decimal_places=3, max_digits=10)),
                ('fotoproduto', models.FileField(blank=True, db_column='FotoProduto', max_length=1000, null=True, upload_to='uploads/%Y/%m')),
                ('hide', models.BooleanField(db_column='HIDE')),
                ('fkid_categoria', models.ForeignKey(db_column='FKID_Categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Categoriaproduto')),
            ],
            options={
                'db_table': 'Produto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statuscompra',
            fields=[
                ('pkid_status', models.IntegerField(db_column='PKID_Status', primary_key=True, serialize=False)),
                ('descricaostatus', models.CharField(blank=True, db_column='DescricaoStatus', max_length=45, null=True)),
            ],
            options={
                'db_table': 'StatusCompra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statusfabricacao',
            fields=[
                ('pkid_status', models.IntegerField(db_column='PKID_Status', primary_key=True, serialize=False)),
                ('descricaostatus', models.CharField(blank=True, db_column='DescricaoStatus', max_length=45, null=True)),
            ],
            options={
                'db_table': 'StatusFabricacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Statusvenda',
            fields=[
                ('pkid_status', models.IntegerField(db_column='PKID_Status', primary_key=True, serialize=False)),
                ('descricaostatus', models.CharField(blank=True, db_column='DescricaoStatus', max_length=100, null=True)),
            ],
            options={
                'db_table': 'StatusVenda',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('pkid_telefone', models.IntegerField(db_column='PKID_Telefone', primary_key=True, serialize=False)),
                ('ddi', models.IntegerField(db_column='DDI')),
                ('ddd', models.IntegerField(db_column='DDD')),
                ('numero', models.IntegerField(db_column='Numero')),
                ('dt_cadastro', models.DateTimeField(db_column='DT_Cadastro')),
                ('dt_alteracao', models.DateTimeField(db_column='DT_Alteracao')),
                ('hide', models.TextField(db_column='HIDE')),
                ('fkid_usuarioalteracao', models.IntegerField(db_column='FKID_UsuarioAlteracao')),
            ],
            options={
                'db_table': 'Telefone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipopessoa',
            fields=[
                ('pkid_tipopessoa', models.IntegerField(db_column='PKID_TipoPessoa', primary_key=True, serialize=False)),
                ('tipopessoa', models.CharField(db_column='TipoPessoa', max_length=100, unique=True)),
                ('hide', models.BooleanField(db_column='HIDE')),
            ],
            options={
                'db_table': 'TipoPessoa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Unidademedida',
            fields=[
                ('pkid_unidademedida', models.IntegerField(db_column='PKID_UnidadeMedida', primary_key=True, serialize=False)),
                ('unidademedida', models.CharField(db_column='UnidadeMedida', max_length=50, unique=True)),
                ('hide', models.BooleanField(db_column='HIDE')),
            ],
            options={
                'db_table': 'UnidadeMedida',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('pkid_usuario', models.IntegerField(db_column='PKID_Usuario', primary_key=True, serialize=False)),
                ('nomecompleto', models.CharField(db_column='NomeCompleto', max_length=45)),
                ('login', models.CharField(db_column='Login', max_length=45, unique=True)),
                ('senha', models.CharField(db_column='Senha', max_length=45)),
                ('dt_importacao', models.DateTimeField(db_column='DT_Importacao')),
                ('dt_alteracao', models.DateTimeField(db_column='DT_Alteracao')),
                ('hide', models.TextField(db_column='HIDE')),
            ],
            options={
                'db_table': 'Usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuarioalteracao',
            fields=[
                ('pkid_usuario_alteracao', models.IntegerField(db_column='PKID_Usuario_Alteracao', primary_key=True, serialize=False)),
                ('dt_alteracao', models.DateTimeField(db_column='DT_Alteracao')),
                ('tipo_alteracao', models.TextField(db_column='Tipo_Alteracao')),
            ],
            options={
                'db_table': 'UsuarioAlteracao',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='fkid_unidademedida',
            field=models.ForeignKey(blank=True, db_column='FKID_UnidadeMedida', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.Unidademedida'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='fkid_tipopessoa',
            field=models.ForeignKey(db_column='FKID_TipoPessoa', on_delete=django.db.models.deletion.DO_NOTHING, to='core.Tipopessoa'),
        ),
        migrations.AlterUniqueTogether(
            name='linhavenda',
            unique_together={('pkid_linhavenda', 'pedidovenda_pkid_venda')},
        ),
        migrations.AlterUniqueTogether(
            name='itemvenda',
            unique_together={('pkid_item', 'pedido_venda_idpedido_venda')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcotacao',
            unique_together={('pkid_item', 'cotacaocompra_pkid_cotacao')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcompra',
            unique_together={('pkid_item', 'pedidocompra_pkid_compra')},
        ),
    ]
